### ISSUE TITLE
10000px height block

### ISSUE THREAD

**Issue by mrspd** [ritzyed/ritzy#23]
Can you tell me for what is needed?

**Comment by rocketraman** [comment]
It makes the line heights consistent when using subscript and subscript. Otherwise the line heights change and the editor content looks like crap.

**Comment by rocketraman** [comment]
BTW if you want to play with it and see the effect of removing it, you can easily modify it in the source here:

https://github.com/ritzyed/ritzy/blob/master/src/components/EditorLineContent.js#L98
