### ISSUE TITLE
how to build and run ritzy-demo

### ISSUE THREAD

**Issue by pentateu** [ritzyed/ritzy#27]
Hi,

I have tried to see the demo online, but it is not working at the moment.

I have tried to run from the source but there is no instructions.

I did:

npm install

npm run start

but the start command does: "start": "node build/server.js"

but there is no build folder.. and there is no build script in the package.json.. and no instruction as how to build..

I have also tried: babel-node src/server.js 

but gives an error:

babel-node src/server.js 
/Volumes/DevCard/Developer/react-stuff/ritzy-demo/node_modules/babel-core/lib/polyfill.js:8
  throw new Error("only one instance of babel/polyfill is allowed");

.. would appreciate build/run instructions in the demo project..

Thanks and keep up with the great work.

**Comment by rocketraman** [comment]
> I have tried to see the demo online, but it is not working at the moment.

The demo should be up and running again.

I'll look into adding instructions for running the demo locally.

**Comment by rocketraman** [comment]
Added instructions in https://github.com/ritzyed/ritzy-demo/commit/18f841ed502030a2ebd7f5f9edf6241e5637e0c9. Hope that helps!

**Comment by rohitsaini81** [comment]
npm i error
can please loot at it



Node.js v18.19.1
npm error code 1
npm error path /home/rohit/Desktop/ritzy-demo
npm error command failed
npm error command sh -c gulp build
npm error A complete log of this run can be found in: /home/rohit/.npm/_logs/2024-06-07T07_38_35_754Z-debug-0.log
