### ISSUE TITLE
Demo website down

### ISSUE THREAD

**Issue by whyhankee** [ritzyed/ritzy#7]
hi, just wanted to let you know that the demo website seems to have a problem.
http://demo-ritzy.rhcloud.com 

>

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.2.15 (Red Hat) Server at demo-ritzy.rhcloud.com Port 80

**Comment by rocketraman** [comment]
Thanks it should be OK now.

**Comment by rocketraman** [comment]
Please note that in the future I'd prefer use of the gitter chat room rather than an issue for this kind of communication, thanks!
