### ISSUE TITLE
Text formatting keyboard shortcuts ignored or inconsistent

### ISSUE THREAD

**Issue by oslego** [ritzyed/ritzy#9]
Keyboard shortcuts for bold, italic, underline, etc., are either completely ignored or highly inconsistent (formatting appears on next operation). No errors thrown in console. Occurs on both Chrome and Safari.

Screen recording where keyboard shortcuts are ignored: 
https://www.youtube.com/watch?v=y6f--TrmT5M

**Comment by rocketraman** [comment]
Oops, looks like my recent optimizations in 7f26302033a600a0220b01b5ff2e1b3fd153659b or 078ff4677cd2ff2264219b042b96a130daf25901 broke the rendering. Ah, the annoyances of not having a comprehensive test suite. Let me take a look.
